### ISSUE TITLE
Implement PLOG reactions for pressure dependence reactions

### ISSUE THREAD

**Issue by jiweiqi** [DENG-MIT/reactorch#3]
Related Materials:
* [Cantera](https://cantera.org/science/reactions.html)
* [Chemkin Pro Theory Manual](https://personal.ems.psu.edu/~radovic/ChemKin_Theory_PaSR.pdf)

**Comment by ZhiyuShi** [comment]
Lines 73, 92, 117-118, 202-239, 260-263, 270-273, and 387-463 in the program attached below were added after I considered the fifth type of reaction, namely P-Log. Their meaning is as follows.
On Line 73, I created a list to store the number of given rate expressions for each reaction, which is only used for the fifth type of reaction.
Lines 92, 117-118 are modeled after reactions of types 1, 2, and 4.
Lines 202-239 are used to store the pressure P, A, b, and Ea of all the given rate expressions for each fifth type reaction. Since there are many rate expressions for a fifth type reaction, P, A, b, and Ea are all lists, created on lines 204-207. It is worth noting that line 203 is very important. I get the number of rate expressions for each fifth type of reaction through cantera's self.gas.reaction(i).rates, which makes the following loops possible. P, A, b, and Ea may all have units, so it is necessary to determine whether they are strings (lines 212-239). There may be multiple units of pressure, such as atm and MPa. These two pressure units are processed on lines 215-218. If there are other pressure units, similar treatment is required.
Lines 260-263 and 270-273 are modeled after the reactions of types 1, 2, and 4.
Lines 387-463 are used to calculate the rate constant of the fifth type of reaction. First calculate rate expressions at all given pressures, and then find out which pressure range the actual pressure is in. I set four variables, jhigh1, jhigh2, jlow1, jlow2. The variable "jhigh1" corresponds to the first Arrhenius expression given at the minumum pressure higher than actual pressure. Considering multiple rate expressions may be given at the same pressure, we need "jhigh2", which corresponds to the last Arrhenius expression given at the minumum pressure higher than actual pressure. The variable "jlow1" corresponds to the last Arrhenius expression given at the maximum pressure lower than actual pressure while "jlow2" corresponds to the first. After determining these four variables, three cases were discussed separately. The three cases are that the actual pressure is higher than all given pressures, the actual pressure is lower than all given pressures, and the actual pressure is higher than the minimum given pressure and lower than the maximum given pressure.

**Comment by ZhiyuShi** [comment]
The modified program can be found here.
https://github.com/ZhiyuShi/reactorch/blob/master/reactorch/Solution.py

**Comment by ZhiyuShi** [comment]
I conducted a lot of tests and I ran the test programs (including Solution_test.py, constant_pressure_autoignition, Speed_test.py) and found no problems.
But I have questions about two details.
The first is, what is the actual pressure? "self.P" is a tensor with a size of 3177*1. When I wrote the program, I thought that the actual pressure value was self.P[0]. Is this correct?
The second is that there are many Arrhenius expressions for each fifth type of reaction. On lines 270-273, I assign A, b, Ea of the first Arrhenius expression to self.Arrhenius_coeffs. Is there any problem with this?
