### ISSUE TITLE
Investigate the sensitivity of this non-negative epsilon

### ISSUE THREAD

**Issue by jiweiqi** [DENG-MIT/reactorch#8]
https://github.com/DENG-MIT/reactorch/blob/83928c5d345859da2d2abf2ebeb7803ee2612fa7/reactorch/Solution.py#L301

Since ReacTorch is trying to utilize the benefit of matrix evaluation, we try to vectorize every operation.

* Across multiple mechanisms
* If a single value not works everywhere, we might come up some suggestions, e.g., 1e-100, 1e-30?

**Comment by jiweiqi** [comment]
Another approach is to compute the reaction rates in conventional way, rather than using a log transformation.

**Comment by ZhiyuShi** [comment]
The figure below shows the average absolute error of temperature as a function of the opposite of the exponent of eps. It can be seen that when the value of eps is 1e-10, the error is very large, about 392.7. When the value of eps drops to 1e-20, the error has dropped by about an order of magnitude, but still large. When the value of eps drops to 1e-22, the error drops suddenly to about 0.1. If eps continues to reduce, the error will no longer change significantly. Since the error of 0.1 is negligible compared with the value of temperature, the calculation result is very accurate when eps takes a value less than 1e-22.
![Average absolute error of temperature_-log(eps)](https://user-images.githubusercontent.com/66129026/85493672-e4ee3a00-b609-11ea-8eb6-d7b3bd76d90a.png)

**Comment by WeilunQiu** [comment]
We perform some test on the auto-ignition case with different epsilon (eps) setting, and a similar conclusion is obtained that eps should be less than 1e-22. The temperature-time relation of the test case is given as follows.
![eps_test_T](https://user-images.githubusercontent.com/41820879/85496770-6eecd180-b60f-11ea-8f52-662599504f04.png)
![eps_test_T](https://user-images.githubusercontent.com/41820879/85496814-82983800-b60f-11ea-8483-e37b9fb39450.png)
